// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: deskbuddyUi

#include "../ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_TextArea1 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextArea1 = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextArea1, 240);
lv_obj_set_height( ui_TextArea1, 240);
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_TextArea1= NULL;

}
