// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: deskbuddyUi

#include "../ui.h"

lv_obj_t *uic_Image2;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 3000, 2, &ui_Screen2_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      Opacitychange_Animation(ui_Image2, 0);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_ready_png);
lv_obj_set_width( ui_Image2, 250);
lv_obj_set_height( ui_Image2, 250);
lv_obj_set_x( ui_Image2, 1 );
lv_obj_set_y( ui_Image2, 1 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
uic_Image2 = ui_Image2;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_Image2= NULL;
ui_Image2= NULL;

}
